#!/usr/bin/env python3
import argparse
import socket
import sys

def start_server(host, port, storage, verbose):
    # Codigo plantilla, ni hay un stop
    print(f"Escuchando en {host}:{port}...")

def main():
    parser = argparse.ArgumentParser(
        description="TP1: Aplicación de arranque del servidor de carga-descarga"
    )

    # Mutuamente excluyente verborreico y silencioso
    grupoExcluyente = parser.add_mutually_exclusive_group()
    grupoExcluyente.add_argument('-v', '--verbose', action='store_true', help='Aumentar verbosidad')
    grupoExcluyente.add_argument('-q', '--quiet', action='store_true', help='Disminuir verbosidad')

    # Obligatorios 
    parser.add_argument('-H', '--host', type=str, default='127.0.0.1', help='Dirección IP del servidor')
    parser.add_argument('-p', '--port', type=int, required=True, help='Puerto del servidor')
    parser.add_argument('-s', '--storage', type=str, required=True, help='Ruta donde iniciar el servidor')

    args = parser.parse_args()

    # argparse hace automaticamente el -h y el --help

    # """"""Simulacion""""""
    try:
        start_server(args.host, args.port, args.storage, args.verbose)
    except KeyboardInterrupt:
        print("\nServidor finalizado por el usuario.")
        sys.exit(0)

if __name__ == "__main__":
    main()