#!/usr/bin/env python3
import argparse
import socket
import sys
import os
import empaquetar

def coinciden_paquetes(ack, ack_esperado):
    return ack == ack_esperado

def main():
    parser = argparse.ArgumentParser(
        description="TP1: Aplicación de transferencia de archivos (Upload)"
    )

    # Mutuamente excluyente verborreico y silencioso
    grupoExcluyente = parser.add_mutually_exclusive_group()
    grupoExcluyente.add_argument('-v', '--verbose', action='store_true', help='Aumentar verbosidad')
    grupoExcluyente.add_argument('-q', '--quiet', action='store_true', help='Disminuir verbosidad')

    # Obligatorios 
    parser.add_argument('-H', '--host', type=str, default='127.0.0.1', help='Dirección IP del servidor')
    parser.add_argument('-p', '--port', type=int, required=True, help='Puerto del servidor')
    parser.add_argument('-s', '--src', type=str, required=True, help='Ruta del archivo a subir')
    parser.add_argument('-n', '--name', type=str, required=True, help='Nombre del archivo en el servidor')
    

    parser.add_argument('-r', '--protocol', default='stop-and-wait', choices=['stop-and-wait', 'selective-repeat'], help='Protocolo de recuperación de errores')

    args = parser.parse_args()

    # argparse hace automaticamente el -h y el --help

    # """"""Simulacion de subida""""""
    #print(f"Iniciando subida de: {args.src}")
    #print(f"Destino: {args.host}:{args.port} con el nombre {args.name}")
    #print(f"Usando protocolo: {args.protocol}")

    if not os.path.exists(args.src):
        print(f"[!] Error: El archivo {args.src} no existe.")
        return

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    try:
        with open(args.src, "rb") as f:
            # --- FASE 1: HANDSHAKE ---
            # Todavia no se tiene en cuenta que hay que avisarle
            # al server por un path mal o un archivo que no existe
            # ni tampoco el timeout
            np_cliente = 0
            ack_cliente = 0
            
            header_init = empaquetar.build_control_byte(init=True, upload=True)
            packet_init = empaquetar.create_packet(np_cliente, ack_cliente, header_init, args.name.encode())
            sock.sendto(packet_init, (args.host, args.port))
            
            res_init, addr = sock.recvfrom(empaquetar.MAX_PACKET_SIZE)
            np_res, ack_res, flags_res, _, _ = empaquetar.unpack_header(res_init)
            
            if not (empaquetar.is_init(flags_res) and ack_res == 1):
                print("[!] Error en el handshake. Abortando.")
                return

            # --- FASE 2: TRANSFERENCIA ---
            np_cliente = 1
            while True:
                chunk = f.read(empaquetar.MAX_DATA_SIZE)
                if not chunk:
                    break 
                
                packet = empaquetar.create_packet(np_cliente, ack_res, empaquetar.build_control_byte(), chunk)
                sock.sendto(packet, (args.host, args.port))
                
                # ESPERAMOS EL ACK (Aquí es donde el cliente se vuelve 'Stop & Wait')
                res_data, addr = sock.recvfrom(empaquetar.MAX_PACKET_SIZE)
                _, ack_servidor, flags_err, _, _ = empaquetar.unpack_header(res_data)
                
                # Si el servidor nos pide el siguiente paquete, avanzamos
                if ack_servidor == np_cliente + 1:
                    np_cliente += 1
                else:
                    # lógica de retransmisión
                    pass

        # --- FASE 3: CIERRE ---
        header_close = empaquetar.build_control_byte(close=True)
        sock.sendto(empaquetar.create_packet(0, 0, header_close, b""), (args.host, args.port))
        print("[+] Transferencia completa. Señal de fin enviada.")

    except OSError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()